### PR TITLE
New feature: Pandoc 2.0 support

### PR DESCRIPTION
**Pull request by ThoseGrapefruits**
Hi there! I came across your project on [Lobsters](https://lobste.rs/t/show). Great work! I ran into some issues running it under Pandoc 2.0 (released a couple of weeks ago, I think) so I wanted to dive in and see what was up.

## Problem
Pandoc 2.0 no longer supports `-S` or `--smart` arguments. The new format is to use a `+smart` or `-smart` extension on the format itself.

## Error Message
```console
RuntimeError: Pandoc died with exitcode "2" during conversion: --smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
```

I tested this only under Pandoc 2.0. I'm assuming that this new format was introduced a while ago, and the old one was only just now deprecated, so hopefully recent versions of Pandoc 1.x support `+smart` as an extension. It would be worth testing under Pandoc 1.x and making sure that's the case before merging this.

### CODE REVIEW

**Comment by ThoseGrapefruits** [comment]
Oops, accidentally force pushed to my branch somehow and deleted my changes. Could you reopen this? I readded them.

**Comment by apas** [comment]
My bad; I accidentally messed up the remote branches and your fork history trying to push a new commit in your PR. I'm aware of Pandoc 2.x breaking things but having mine pinned on 1.19.x I forgot about it. I added a version check atop your commit at b364a58 in the ThoseGrapefruits-master branch. Check it out and if you can update your PR with it, it'd be great. (So we can maintain commit history.)

However, I will not be able to merge this until a CSS bug produced by `+smart` is fixed. Images are misaligned. See below for reference.

screenshot 2017-11-12 21 57 24

screenshot 2017-11-12 21 56 55

**Comment by ThoseGrapefruits** [comment]
Ah I see. Ok, I updated the PR with your changes as well. Hopefully that bug gets fixed soon!

**Comment by apas** [comment]
Thanks, looks good. I will investigate the CSS bug and report back.

**Comment by ThoseGrapefruits** [comment]
This looks like an issue with the modified version of `tufte.css` being used. The [current `tufte.css` version](https://github.com/edwardtufte/tufte-css/blob/gh-pages/tufte.css#L126) has moved to using the `<figure>` element instead of the `<div class="figure">`, which matches what is being generated for me locally. I think pulling in those updates to the `figure` CSS entry should fix it.

**Comment by apas** [comment]
This points toward the right direction.

[Current `figure` in `tufte.css`](https://github.com/edwardtufte/tufte-css/blob/gh-pages/tufte.css#L126), however, is referenced within the following HTML structure

```html
<p> . . . </p> <!-- paragraph above -->
<figure>
  <label for="mn-exports-imports" class="margin-toggle">⊕</label>
  <input type="checkbox" id="mn-exports-imports" class="margin-toggle">
  <span class="marginnote">From Edward Tufte, <em>Visual Display of Quantitative
      Information</em>, page 92.</span>
  <img src="img/exports-imports.png" alt="Exports and Imports to and from Denmark &amp;
      Norway from 1700 to 1780">
</figure>
<p> . . . </p> <!-- paragraph below -->
```

whereas Pandoc produces the following HTML

```html
<p> . . . </p> <!-- paragraph above -->
<figure>
  <img src="/static/img/figure1.png" title="An image." alt="Figure 1: A note about the image."
      id="fig:test">
  <figcaption>Figure 1: A note about the image.</figcaption>
</figure>
<p> . . . </p> <!-- paragraph below -->
```

which aligns the image properly, yet on the other hand, botches the margin note caption.

screenshot 2017-11-12 23 48 46

I can try to rearrange it in `resources.js`. Another option is a custom Pandoc filter.

**Comment by apas** [comment]
On second thought, a `resources.js` implementation complicates backwards compatibility for Pandoc 1.x, whereas with a Pandoc filter it's much easier to guarantee it.

**Comment by apas** [comment]
Fixed in 4c3b9fc in `ThoseGrapefruits-master` by rearranging using `resources.js`. I tested for both Pandoc 2.x and 1.x in order to guarantee backwards compatibility and works fine on Safari 11.0.1. You can find an adjusted `hackers.md` test post with multiple images (in order to test for caption and figure 1:1 correspondence) [here](https://www.pastery.net/znvttr/raw/). Pull the changes, test in your environment, and add the commit (w/o the amended test post) in your PR so I can merge.

PS. Removed an extra conditional check in a636b3a as well.

**Comment by ThoseGrapefruits** [comment]
Looks good in my testing across current Chrome, Firefox, and Safari.

**Comment by apas** [comment]
Merged.

**Pull request merged**
